### ISSUE TITLE
(Android) Carrier Profile

### ISSUE THREAD

**Issue by BurakDrg** [BurakDrg/Return#15]

**Comment by canberksakarya** [comment]
Bu ekranda;

- Kurye Adı,

- Kurye Numarası,

- Teslimat Alanı,

- Araç Plakası,

dışında yer vermem gereken başka bir bilgi var mı? Yoksa bu kadar bilgi yeterli mi?
Bu bilgilerin kuryenin kendisi tarafından değil, şirket tarafından güncellenip değiştirilebileceğini varsayıyorum.

**Comment by canberksakarya** [comment]
Courier Profile Activity has been updated to show the requested data on screen. However shown data is currently stored locally.
